# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f16f5fd0703534f5105c2f867d40051f4c178de2b35ea0a2b4977e9b3a8e33ebf410857852806a6e632b556d3c2a80f8a1bbfde64913291727c1d2c40d644ae

test:
  secret_key_base: ee39bcac3f2ce3ed889cf3471edd2329be8725304315253c9bd1e446740bc2bb118f6ac9ef6183f5e4bb49accbc1df3d7bbef05ad90f67980ce647187a4757c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
